
<header><h3>Wstaw plik</h3></header>

<? $labelType = (!empty($this->type) ? '_'.strtolower($this->type) : '');?>

<form id="jInsertAttachmentForm" action="/attachment/user.tinyplugin/file.save" method="post"<?= empty($this->attach) ? ' class="hide"' : '';?>>
        
    <input type="hidden" id="jAttId" name="att_id" value="<?= $this->attach ? $this->attach->id : '';?>"/>
    
    <div class="row-fluid">

        <div id="jFirstAttachment" class="span2">
        <? if(!empty($this->attach)) :?>
        
            <?if($this->attach->isImage()):?>
                <img src="<?= $this->mdsImage($this->attach, array('resize' => '150x150')); ?>" title="<?= $this->escape($this->attach->description);?>" />
                <span><?= $this->escape($this->attach->name);?></span>
            <?elseif($this->attach->isVideo()):?>
                <?= $this->mdsVideoThumb($this->attach, array('resize' => '0x150')); ?>
                <span><?= $this->escape($this->attach->name);?></span>
            <?else:?>
            <div class="info">
                <i class="icon-file"></i>
                <span><?= $this->escape($this->attach->name);?></span>
            </div>
            <?endif?>
            
        <? endif;?>
        </div>
        
        <div class="span10">
            <p><textarea class="input-xxlarge" id="jFirstDescription" name="att_description"><? if($this->attach) :?><?= $this->attach->description;?><?endif;?></textarea></p>
        </div>
    </div>

    <button type="submit" class="btn btn-success">Wstaw do edytora</button>

    <a class="btn btn-primary" href="/attachment/user.tinyplugin/file.choose">Wybierz inny plik z bazy</a>

</form>

<div id="jInsertAttachmentInit"<?= (!empty($this->attach) ? ' class="hide"' : '');?>>
    <a class="btn btn-primary jAddFileButton" onclick="$('input[id=fileupload]').click()">Wgraj plik</a>
    <a class="btn btn-primary jChooseFileButton" href="/attachment/user.tinyplugin/file.choose">Wybierz z bazy</a>
</div>

<form method="post" enctype="multipart/form-data">
<input style="display: none;" id="fileupload" type="file" name="uploader_att_url" data-url="/attachment/user.tinyplugin/upload.file/type/file/parentId/<?= $this->attach->id;?>" multiple>
</form>

<div id="jProgress" class="progress uploadProgress">
    <div class="bar" style="width: 0%;"></div>
</div>

<? $this->headScript()->appendFile('/file_uploader/js/jquery.iframe-transport.js');?>
<? $this->headScript()->appendFile('/file_uploader/js/jquery.fileupload.js');?>

<? $this->inlineScript()->appendScript($this->render('user-tinyplugin/uploader.js')); ?>
<? $this->inlineScript()->appendScript($this->render('user-tinyplugin/file.js')); ?>





