
# kolumny i ich zawartosc
layout:
  container:
    tag: div
    attribs:
      class: profile-layout
  rows:
    - 
      container:
        attribs:
          class: row-fluid
      columns:
        - 
          container:
            attribs:
              class: span12
          boxes:
            userTopInfo:
              type: box
              className: PublicInfo
              module: profile
              container:
                tag: div
                attribs:
                  class:  dboxes
  
    - 
      container:
        attribs:
          class: row-fluid
      columns:
        - 
          container:
            attribs:
              id: content
              class: span12
          boxes:
            content:
              type: content
              container:
                tag: div
                attribs:
                  id: content

  