
# kolumny i ich zawartosc
layout:
  container:
    tag: div
    attribs:
      id: layout
  rows:
    - 
      container:
        attribs:
          class: row-fluid
      columns:
        - 
          container:
            attribs:
              id: content
              class: span12
          boxes:
            content:
              type: content
              container:
                tag: div
                attribs:
                  id: content

  
segments:
  boxSEG:
    type: box
    className: Test
    module: default
    container:
      tag: div
      attribs:
        class: dboxes
    params:
      space: 500
      default: 600


